version: '2'
services:
  infinispan-server1:
    image: digite/sk-infinispan-server:10.1.8    
    container_name: infinispanserver1          
    environment:
      - TZ=Asia/Kolkata
      - USER=admin
      - PASS=password
      - PORTPLUS=0   
    ports:
      - 11222:11222

  infinispan-server2:
    image: digite/sk-infinispan-server:10.1.8    
    container_name: infinispanserver2      
    environment:
      - TZ=Asia/Kolkata
      - USER=admin
      - PASS=password
      - PORTPLUS=100    
    ports:
      - 11322:11222
        
